description: "Brief executive summary template for meeting highlights and key decisions"
version: "1.0"
arguments:
  - name: "meeting_date"
    description: "Date of the meeting"
    required: true
  - name: "meeting_title"
    description: "Title or subject of the meeting"
    required: true
  - name: "transcript"
    description: "Full meeting transcript to analyze"
    required: true
metadata:
  tags:
    - meetings
    - summary
    - executive
  suggested_use: "Use for quick summaries and executive briefings"
  output_format: "markdown"